defaults:
  - _self_
  - model: conformer
  - data: custom
  - optimizer: adamw
  - decoder: beam_search

train:
  batch_size: 32
  epochs: 100
  learning_rate: 2e-5
  accelerator: 'auto'
  precision: '16-mixed'
  checkpoint: checkpoints/conformer49.ckpt

